### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by SebRut** [twisterghost/jankbot#17]
This happened after I updated the node dependencies.
```
sebrut@indus jankbot]$ ./jankbot 
Loading module About by SebRut...
Loading module Hero Stats by JankDota...
Loading module Quotes by JankDota...
Loading module Whois by JankDota...
Loading module Wiki by JankDota...
Loaded 5 module(s).

/home/sebrut/jankbot/node_modules/steam/lib/steam_client.js:150
  var cryptedSessKey = require('crypto').publicEncrypt(fs.readFileSync(__dirna
                                         ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at SteamClient.handlers.(anonymous function) (/home/sebrut/jankbot/node_modules/steam/lib/steam_client.js:150:42)
    at SteamClient._netMsgReceived (/home/sebrut/jankbot/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (/home/sebrut/jankbot/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Connection.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

**Comment by twisterghost** [comment]
What do you mean by updating node dependencies? Installed using the ones defined in package.json?

**Comment by twisterghost** [comment]
It seems this is an issue introduced by version 0.6.8 of the steam dependency. I will make a change to lock the dependency version to `0.6.6` instead of `~0.6.6`

**Comment by twisterghost** [comment]
Version 2.0.1 has been published with the fix.
